# Generated by Django 3.1.6 on 2021-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('Disease', models.CharField(max_length=70)),
                ('doctor', models.CharField(max_length=50)),
                ('doctor_fees', models.IntegerField(default=500)),
                ('admit_date', models.DateField()),
            ],
        ),
    ]
